export const ErrorKeys = {
  AUTH: {
    WRONG_EMAIL_OR_PASSWORD: 'WRONG_EMAIL_OR_PASSWORD',
    EMAIL_ALREADY_TAKEN: 'EMAIL_ALREADY_TAKEN',
  },
  GAME: {
    GAME_ALREADY_STARTED: 'GAME_ALREADY_STARTED',
    GAME_ALREADY_FINISHED: 'GAME_ALREADY_FINISHED',
  },
};
